# Generated by Django 5.2.8 on 2025-11-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otprequest_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Số điện thoại liên hệ', max_length=20, null=True),
        ),
    ]
