# Generated by Django 5.2.8 on 2025-11-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_full_name_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Vĩ độ GPS của shipper (để phân luồng đơn hàng)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, help_text='Thời điểm cập nhật vị trí GPS lần cuối', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Kinh độ GPS của shipper (để phân luồng đơn hàng)', max_digits=9, null=True),
        ),
    ]
