# Generated by Django 5.2.8 on 2025-11-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_menuitem_options_alter_merchant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL ảnh đại diện của cửa hàng', max_length=500, null=True),
        ),
    ]
