# Generated by Django 5.2.8 on 2025-11-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_merchant_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Ảnh món ăn', null=True, upload_to='menu_items/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL ảnh (fallback nếu không có file)', max_length=500, null=True),
        ),
    ]
