# Generated by Django 5.2.8 on 2025-11-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_menuitem_image_alter_menuitem_image_url'),
    ]

    operations = [
        # Index cho Merchant - tối ưu tìm kiếm theo vị trí
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_merchant_location 
                ON menus_merchant(latitude, longitude) 
                WHERE latitude IS NOT NULL AND longitude IS NOT NULL;
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_merchant_location;
            """
        ),
        # Index cho Merchant - tối ưu filter is_active
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_merchant_active 
                ON menus_merchant(is_active) 
                WHERE is_active = true;
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_merchant_active;
            """
        ),
        # Index cho MenuItem - tối ưu join với Merchant
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_menuitem_merchant 
                ON menus_menuitem(merchant_id);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_menuitem_merchant;
            """
        ),
        # Index cho MenuItem - tối ưu filter is_available
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_menuitem_available 
                ON menus_menuitem(is_available) 
                WHERE is_available = true;
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_menuitem_available;
            """
        ),
        # Composite index cho MenuItem - tối ưu query phổ biến
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_menuitem_merchant_available 
                ON menus_menuitem(merchant_id, is_available) 
                WHERE is_available = true;
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_menuitem_merchant_available;
            """
        ),
    ]
